name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: siosios/metrics@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output_action: commit
          committer_message: "chore: update metrics"
          retries: 3
          retries_delay: 900
          optimize: css, xml

          # Options
          user: siosios
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: America/Chicago
          plugin_stars: yes
          plugin_stars_limit: 4
